# Generated by Django 2.1.7 on 2019-04-03 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='N/A', max_length=250)),
                ('priority', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('review_correct', models.IntegerField(default=0)),
                ('review_total', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statements.Statement')),
            ],
        ),
    ]
