# Generated by Django 2.1.7 on 2019-03-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='note',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='progress',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statements.Statement'),
        ),
    ]
