# Generated by Django 2.1.7 on 2019-03-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_collection',
        ),
    ]
