# Generated by Django 2.1.7 on 2019-03-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collecs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no-image.png', upload_to='statements/%Y/%m')),
                ('statement', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=25)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collecs.Collection')),
            ],
        ),
    ]
