# Generated by Django 2.1.7 on 2019-03-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_auto_20190331_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='statements/%Y/%m'),
        ),
    ]
