# Generated by Django 2.1.7 on 2019-03-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collecs', '0001_initial'),
        ('usersettings', '0002_auto_20190326_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='active_sub',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='active_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='collecs.Collection'),
        ),
    ]
