# Generated by Django 2.1.7 on 2019-04-03 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collecs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_count', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(default=datetime.datetime.now)),
                ('rating', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collecs.Collection')),
            ],
        ),
    ]
