# Generated by Django 2.1.7 on 2019-03-26 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collecs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_auto_20190326_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collecs.Collection'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'collection')},
        ),
    ]
