# Generated by Django 2.1.7 on 2019-03-30 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20190326_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_reviewed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
