# Generated by Django 2.1.7 on 2019-04-03 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='no-image.png', upload_to='collections/%Y/%m')),
                ('description', models.TextField(blank=True)),
                ('size', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(default=datetime.datetime.now)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
